# -*- coding: utf-8 -*-
"""coco.ipynb

Generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vBj-Bh__eF_zbb3X3Wn-yiPXNjSHNwdM
"""

from google.colab import drive
drive.mount('/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd ../gdrive/MyDrive/Deep Learning Project/Code

!git clone https://github.com/nightrome/cocostuff.git

# Commented out IPython magic to ensure Python compatibility.
# %cd cocostuff

# Download everything
!wget --directory-prefix=downloads http://images.cocodataset.org/zips/train2017.zip
!wget --directory-prefix=downloads http://images.cocodataset.org/zips/val2017.zip
!wget --directory-prefix=downloads http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip

# Unpack everything
!mkdir -p dataset/images
!mkdir -p dataset/annotations
!unzip downloads/train2017.zip -d dataset/images/
!unzip downloads/val2017.zip -d dataset/images/
!unzip downloads/stuffthingmaps_trainval2017.zip -d dataset/annotations/

!git clone https://github.com/zyang-ur/ReSC.git

bash ln_data/download_data.sh --path ./ln_data